export const COUNTRY_NAMES_MAP = {
  Argentina: "Argentine",
  Australia: "Australie",
  Austria: "Autriche",
  Belgium: "Belgique",
  Bosnia: "Bosnie",
  Bulgaria: "Bulgarie",
  Canada: "Canada",
  "Channel Islands": "Îles Anglo-Normandes",
  "China/Hong Kong": "Hong Kong",
  Croatia: "Croatie",
  "Croatia (Modern)": "Croatie (Actuelle)",
  Cuba: "Cuba",
  Denmark: "Danemark",
  Egypt: "Égypte",
  England: "Angleterre",
  Finland: "Finlande",
  France: "France",
  Germany: "Allemagne",
  Greece: "Grèce",
  Guyana: "Guyanne",
  Hungary: "Hongrie",
  India: "Inde",
  Ireland: "Irelande",
  Italy: "Italie",
  Japan: "Japon",
  Latvia: "Lettonie",
  Lebanon: "Liban",
  NA: "Inconnu",
  Netherlands: "Pays-Bas",
  "Northern Ireland": "Irelande du Nord",
  Norway: "Norvège",
  Peru: "Pérou",
  Poland: "Pologne",
  Russia: "Russie",
  Scotland: "Écosse",
  Siam: "Thaïlande",
  "Slovakia (Modern day)": "Slovaquie (Actuelle)",
  Slovenia: "Slovénie",
  "South Africa": "Afrique du Sud",
  Spain: "Espagne",
  Sweden: "Suède",
  Switzerland: "Suisse",
  Syria: "Syrie",
  Turkey: "Turquie",
  "United States": "États-Unis",
  Uruguay: "Uruguay",
  Wales: "Pays de Galles",
  Yugoslavia: "Yugoslavie",
};
